package com.potato112.springservice.domain.user.model;

import com.potato112.springservice.domain.common.SysMapper;
import com.potato112.springservice.domain.user.model.authorize.UserVo;
import com.potato112.springservice.repository.entity.User;

public class UserMapper implements SysMapper<User, UserVo> {

    @Override
    public UserVo mapToVo(User user) {

        UserVo userVo = new UserVo();
        //userVo.setId(user.getId()); // autogenerated not provided
        userVo.setFirstName(user.getFirstName());
        userVo.setLastName(user.getLastName());
        userVo.setEmail(user.getEmail());
        userVo.setPassword(user.getPassword());
        userVo.setPhone(user.getPhone());
        userVo.setLocked(user.getLocked());

        // TODO implement Grops mapping
        return userVo;
    }

    @Override
    public User mapToEntity(UserVo modelVo) {

        User user = new User();
        //user.setId(modelVo.getId());
        user.setFirstName(modelVo.getFirstName());
        user.setLastName(modelVo.getLastName());
        user.setEmail(modelVo.getEmail());
        user.setPassword(modelVo.getPassword());
        user.setPhone(modelVo.getPhone());
        user.setLocked(modelVo.getLocked());

        // TODO implement Grops mapping
        return user;
    }

}
